[package]
name = "picross-solver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.34", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
rstest = "0.25.0"
